# Record Linkage: Machine Learning Example

This example will walk you through a typical record linkage application using the recordlinkage package in Python. We will quickly address every step and end with setting up a machine learning model to classify record pairs. The steps we will be talking about are: 

1. The Principles of Record Linkage
1. Data Pre-processing
2. Indexing
3. Record Comparison
4. Classification 
5. Evaluation

In [1]:
# load packages 
import recordlinkage 
import pandas
import sklearn
import numpy
import scipy
import jellyfish
from recordlinkage.datasets import load_febrl4
from recordlinkage.standardise import clean
from recordlinkage.standardise import phonetic

## The Principles of Record Linkage
The goal of record linkage is to determine if pairs of records describe the same identity. For instance, this is important for removing duplicates from a data source or joining two separate data sources together. Record linkage also goes by the terms data matching, merge/purge, duplication detection, de-duping, reference matching, entity resolution, disambiguation, co-reference/anaphora in various fields.

There are several approaches to record linkage that include 
    - exact matching, 
    - rule-based linking and 
    - probabilistic linking. 
- An example of **exact matching** is joining records based on social security number. This is what you already have done in SQL by joining tables by an unique identifier. 
- **Rule-based matching** involves applying a cascading set of rules that reflect the domain knowledge of the - records being linked. 
- In **probabilistic record linkages**, linkage weights are estimated to calculate the probability of a certain match.

In practical applications you will need record linkage techiques to combine information addressing the same entity that is stored in different data sources. Record linkage will also help you to address the quality of different data sources. For example, if one of your databases has missing values you might be able to fill those by finding an identical pair in a different data source. Overall, the main applications of record linkage are
    1. Merging two or more data files 
    2. Identifying the intersection of the two data sets 
    3. Updating data files (with the data row of the other data files) and imputing missing data
    4. Entity disambiguation and de-duplication

In [2]:
# use expample data that come with the package
dfA, dfB = load_febrl4()

In [3]:
# How does the first dataset look
dfA.head()

,given_name,surname,street_number,address_1,address_2,suburb,postcode,state,date_of_birth,soc_sec_id
rec_id,,,,,,,,,,
rec-1070-org,michaela,neumann,8,stanley street,miami,winston hills,4223,nsw,19151111,5304218
rec-1016-org,courtney,painter,12,pinkerton circuit,bega flats,richlands,4560,vic,19161214,4066625
rec-4405-org,charles,green,38,salkauskas crescent,kela,dapto,4566,nsw,19480930,4365168
rec-1288-org,vanessa,parr,905,macquoid place,broadbridge manor,south grafton,2135,sa,19951119,9239102
rec-3585-org,mikayla,malloney,37,randwick road,avalind,hoppers crossing,4552,vic,19860208,7207688

In [4]:
# How does the second dataset look
dfB.head()

,given_name,surname,street_number,address_1,address_2,suburb,postcode,state,date_of_birth,soc_sec_id
rec_id,,,,,,,,,,
rec-561-dup-0,elton,NaN,3,light setreet,pinehill,windermere,3212,vic,19651013,1551941
rec-2642-dup-0,mitchell,maxon,47,edkins street,lochaoair,north ryde,3355,nsw,19390212,8859999
rec-608-dup-0,NaN,white,72,lambrigg street,kelgoola,broadbeach waters,3159,vic,19620216,9731855
rec-3239-dup-0,elk i,menzies,1,lyster place,NaN,northwood,2585,vic,19980624,4970481
rec-2886-dup-0,NaN,garanggar,NaN,may maxwell crescent,springettst arcade,forest hill,2342,vic,19921016,1366884

## Data Pre-processing

Data pre-processing is an important step in a data anlysis project in general, in record linkage applications in particular. The goal of pre-processing is to transform messy data into a dataset that can be used in a project workflow.

Linking records from different data sources comes with different challenges that need to be addressed by the analyst. The analyst must determine whether or not two entities (individuals, businesses, geographical units) on two different files are the same. This determination is not always easy. In most of the cases there is no common uniquely identifing characteristic for a entity. For example, is Bob Miller from New Yor the same person as Bob Miller from Chicago in a given dataset? This detemination has to be executed carefully because consequences of wrong linkages may be substantial (is person X the same person as the person X on the list of identified terrorists). Pre-processing can help to make better informed decisions.

Pre-processing can be difficult because there are a lot of things to keep in mind. For example, data input errors, such as typos, misspellings, truncation, abbreviations, and missing values need to be corrected. Literature shows that preprocessing can improve matches. In some situations, 90% of the improvement in matching efficiency may be due to preprocessing. The most common reason why matching projects fail is lack of time and resources for data cleaning. 

The record linkage package comes with a "clean" add on which can help you with preprocessing. Recordlinkage’s standardise sub-module includes four built-in functions. Each of these functions tackle a different aspect of pre-processing.

In [5]:
## The clean() function is used to clean a single column within a data frame, where the column contains strings. 
## By default, clean() will turn all strings into lowercase and remove characters such as quotation marks & punctuation.

dfA["name_clean"] = clean(dfA["given_name"])
dfB["name_clean"] = clean(dfB["given_name"])

In [6]:
## The phonetic() function is used to convert strings into their corresponding phonetic codes. 
## This is particularly useful when comparing names where different possible spellings make it difficult to find 
## exact matches (Ex. Jillian and Gillian).

dfA["phonetic"] = phonetic(dfA["name_clean"], method="nysiis")
dfB["phonetic"] = phonetic(dfB["name_clean"], method="nysiis")

In [27]:
# How does the second dataset look
dfA.head(100)

,given_name,surname,street_number,address_1,address_2,suburb,postcode,state,date_of_birth,soc_sec_id,name_clean,phonetic
rec_id,,,,,,,,,,,,
rec-1070-org,michaela,neumann,8,stanley street,miami,winston hills,4223,nsw,19151111,5304218,michaela,MACAL
rec-1016-org,courtney,painter,12,pinkerton circuit,bega flats,richlands,4560,vic,19161214,4066625,courtney,CARTNY
rec-4405-org,charles,green,38,salkauskas crescent,kela,dapto,4566,nsw,19480930,4365168,charles,CARL
rec-1288-org,vanessa,parr,905,macquoid place,broadbridge manor,south grafton,2135,sa,19951119,9239102,vanessa,VANAS
rec-3585-org,mikayla,malloney,37,randwick road,avalind,hoppers crossing,4552,vic,19860208,7207688,mikayla,MACAYL
rec-298-org,blake,howie,1,cutlack street,belmont park belted galloway stud,budgewoi,6017,vic,19250301,5180548,blake,BLAC
rec-1985-org,NaN,lund,109,caley crescent,allandale aged care facility,mill park,4053,nsw,19180902,7074690,NaN,NaN
rec-2404-org,blakeston,broadby,53,traeger street,valley of springs,north ward,3083,qld,19120907,4308555,blakeston,BLACASTAN
rec-1473-org,NaN,leslie,925,carpenter close,NaN,canterbury,2340,vic,19950608,2438058,NaN,NaN
rec-453-org,edward,denholm,10,corin place,gold tyne,clayfield,4221,vic,19660306,7119771,edward,EDWAD
rec-4866-org,charlie,alderson,266,hawkesbury crescent,deergarden caravn park,cooma,4128,vic,19440908,1256748,charlie,CARLY
rec-4302-org,molly,roche,59,willoughby crescent,donna valley,carrara,4825,nsw,19200712,1847058,molly,MALY
rec-383-org,angus,mcgregor,1,NaN,rosetta village,chelsea heights,3020,wa,19170409,8677579,angus,ANG
rec-420-org,kate,stephenson,8,sinclair street,brentwood vlge,ryde,5333,sa,19051012,4182623,kate,CAT
rec-3440-org,matthew,bissett,11,cowcher place,kassingbrook,surfers paradise,4037,vic,19121107,5435247,matthew,MATAE
rec-4028-org,lachlan,godfrey,45,lienhop street,sorrento,lalor,2350,sa,19080429,9107241,lachlan,LACLAN
rec-1363-org,campbell,clarke,14,wootton crescent,the manor garden,northmead,3265,vic,19220610,7658745,campbell,CANPBAL
rec-4641-org,jessica,weller,318,bishopbourne court,lismore road,padstow,2191,nsw,19600919,4837774,jessica,JASAC
rec-1300-org,joshua,corbin,83,tweed place,five oaks,keilor,4818,nsw,19721018,7955748,joshua,JAS
rec-4178-org,caitlin,basey,414,pelsart street,st francis vlge,daisy hill,2113,nsw,19110711,7811311,caitlin,CATLAN
rec-4303-org,alessandra,stanley,9,araluen street,bombowlee,avoca,3104,qld,19940325,8650329,alessandra,ALASANDR
rec-1280-org,francesco,cannell,5,ngunawal drive,whispering pines,brighton,7320,nsw,19900219,2439499,francesco,FRANCASC
rec-4137-org,liam,schwaz,1005,elvire place,narada,bronte,2137,tas,19470324,4505367,liam,LAN
rec-1054-org,benjamin,capel,177,clive steele avenue,spq camp,woongarra,4207,qld,19090522,4415928,benjamin,BANJANAN
rec-1826-org,kynan,dooley,92,mcintyre street,apt 27,woollahra,6021,qld,19310924,1493049,kynan,CYNAN
rec-780-org,harrison,boulter,9,macgregor street,stonyridge,cecil plains,3070,nsw,19110312,5094110,harrison,HARASAN
rec-85-org,joselyn,dakin,19,abernethy street,kanangra hostel,manunda,3028,wa,19261205,4852063,joselyn,JASALYN
rec-201-org,claudia,huxley,108,crease place,edellen,north ryde,2464,vic,19441020,9295307,claudia,CLAD
rec-4878-org,NaN,lowry,6,hadleigh circuit,rowethorpe,rossmoyne,2770,sa,19350708,6616912,NaN,NaN
rec-4098-org,lily,warnock,68,darling street,jeran,exton,2154,nsw,19620520,2626334,lily,LALY
...,...,...,...,...,...,...,...,...,...,...,...,...
rec-3020-org,madison,herbert,14,cowie place,old post office,glenmore park,2680,nsw,19950105,9689395,madison,MADASAN
rec-2115-org,pearson,shepherd,13,de graaff street,springdale,beverly hills,2650,vic,19320517,6334586,pearson,PARSAN
rec-2432-org,isaiah,warde,61,mcphail place,sunbury,bonnyrigg,3929,vic,19090111,8475133,isaiah,IS
rec-2740-org,imogen,kiosses,2,quandong street,overnewton,arundel,5024,sa,19751002,1581588,imogen,INAGAN
rec-4792-org,julia,meadows,18,araluen street,st john of god hospital,crows nest,3174,nsw,19160818,7101191,julia,JAL
rec-3756-org,lucinda,burrill,31,bamir square,corridella,inglewood,4557,qld,19471211,4875837,lucinda,LACAND
rec-215-org,caleb,roberts-yates,40,millpost close,bandera,cobar,3500,qld,19670914,5399458,caleb,CALAB
rec-391-org,noah,mason,29,william hudson crescent,court units,elwood,3155,sa,19500215,8353213,noah,N
rec-3897-org,ella,estcourt,12,gellatly place,mayfair,braddon,3850,nsw,19090814,2110759,ella,EL
rec-18-org,riley,kerr-sullivan,166,clem hill street,mindaree,oyster bay,7325,vic,19090429,7355856,riley,RALY
rec-3590-org,nasyah,reid,14,groom street,warrina lakes,goonellabah,2775,nsw,19850813,9822354,nasyah,NASY
rec-3327-org,ella,browne,35,tanjil loop,cedarview,berkeley vale,4564,qld,19480726,6646608,ella,EL
rec-3798-org,michael,cochrane,7,monaro crescent,ballarkona,hendra,4128,qld,19361016,5263623,michael,MACAL
rec-2029-org,benjamin,cassimatis,23,NaN,yacklin,thornleigh,6006,nsw,NaN,1533923,benjamin,BANJANAN
rec-2686-org,imogen,white,12,macrossan crescent,peridon vlge,mount isa,2088,nsw,19580528,9882514,imogen,INAGAN
rec-1807-org,maya,nevin,351,rapanea street,chelsea house,evanston,2033,NaN,19220204,9920408,maya,MAY
rec-1506-org,madeleine,bradshaw,90,burkitt street,mindaree,tuart hill,3300,nsw,19180720,9562529,madeleine,MADALAN
rec-1614-org,jack,moscatt,15,hosking place,NaN,st kilda east,2600,vic,19611218,2565922,jack,JAC
rec-2813-org,georgia,rees,40,maclaurin crescent,spring creek,fullarton,6233,nsw,19210305,5595588,georgia,GARG
rec-1362-org,NaN,collinson,8,parrabel place,fraser lodge,elwood,2420,vic,19100819,5602774,NaN,NaN
rec-2011-org,ruby,grobler,128,lonsdale street,tallinga park,newbridge,2105,qld,19190104,5332690,ruby,RABY
rec-4825-org,lara,dunis,7,rodda place,dry rush,casino,4170,nsw,19580928,2469542,lara,LAR
rec-1483-org,zachariah,steed,24,hamelin crescent,surfers hawaiian,preston beach,4214,nsw,19300502,9340008,zachariah,ZACAR
rec-3075-org,william,vanderwesten,11,william wilkins crescent,wyuna,grenfell,5290,nsw,19500801,2499394,william,WALAN
rec-2010-org,layla,donaldson,71,mannheim street,sandalford homestead,urangan,2713,wa,19320608,5103641,layla,LAYL
rec-4548-org,samantha,chandler,183,macnamara place,st johnof god hospital,greenwith,2047,wa,19011201,6692802,samantha,SANANT
rec-1996-org,alexander,jeffries,45,keartland street,NaN,northbridge,3043,vic,19770408,3206197,alexander,ALAXANDAR
rec-1373-org,talyah,mccarthy,8,carter crescent,eldamead,springwood,2170,nsw,19210913,4421495,talyah,TALY
rec-3232-org,isabelle,hope,140,ellenborough street,grimes paddock cotge,murray bridge,6152,qld,19480522,1334359,isabelle,ISABAL
rec-1007-org,breana,thorpe,54,weipa place,kimberley,san remo,4660,qld,19660117,3264752,breana,BRAN

## Indexing

Indexing allows you to create candidate links, which basically means identifying pairs of data rows which might refer to the same real world entity. This is also called the comparison space (matrix). There are different ways to index data. The easiest is to create a full index and consider every pair a match. This is also the least efficient method, because we will be comparing every row of one dataset with every row of the other dataset.

If we had 10,000 records in data frame A and 100,000 records in data frame B, we would have 1,000,000,000 candidate links. You can see that comparing over a full index is getting inefficient when working with big data.

In [8]:
## Full Index
indexer = recordlinkage.FullIndex()
pairs = indexer.index(dfA, dfB)

WARNING:recordlinkage:The number of record pairs is large. Consider a different indexation algorithm for better performance.

In [9]:
## How many records do we have?
print (len(dfA), len(dfB), len(pairs))

(5000, 5000, 25000000)

We can do better if we actually include our knowledge about the data to eliminate bad link from the start. This can be done through blocking. This method includes only record pairs that are identical on one or more stored attributes of the person (or entity in general). The recordlinkage packages gives you multiple options for this. For example, you can block by using variables, which menas only links exactly equal on specified values will be kept. You can also use a neighbourhood index in which the rows in your dataframe are ranked by some value and python will only link between the rows that are closeby.

In [10]:
## Create Index with blocking
indexer = recordlinkage.BlockIndex(on=('given_name', 'surname'))
pairs = indexer.index(dfA, dfB)

print (len(pairs))

2574

Here, the set of candidate links is restricted to entries with the exact same name. Think carefully about the quality of your data when using this method. If you cannot guarantee exact matches between corresponding rows, you may exclude potential matches from your set of candidate links.

In [29]:
## However, blocking on name might be too restrictive
indexer = recordlinkage.BlockIndex(on='postcode')
pairs = indexer.index(dfA, dfB)

print (len(pairs))

28609

## Record Comparison

After you have created a set of candidate links, you’re ready to begin comparing the records associated with each candidate link. In recordlinkage you must initiate a Compare object prior to performing any comparison functionality between records. This object stores both dataframes, the candidate links, and a vector containing comparison results. Further, the Compare object contains the methods for performing comparisons. The code block below initializes the comparison object.

In [12]:
## Initializes the comparison object
compare_cl = recordlinkage.Compare()

Currently there are five specific comparison methods within recordlinkage: Compare.exact(), Compare.string(), Compare.numeric(), Compare.geo(), and Compare.date(). The Compare.exact() method is simple: if two values are an exact match a comparison score of 1 is returned, otherwise 0 is retured. The Compare.string() method is a bit more complicated and generates a score based on well known string-comparison algorithms (for this example Levenshtein or Jaro Winkler).

In [13]:
compare_cl.string('given_name', 'given_name', method='jarowinkler', threshold=0.85, label='given_name')
compare_cl.string('surname', 'surname', method='jarowinkler', threshold=0.85, label='surname')
compare_cl.exact('date_of_birth', 'date_of_birth', label='date_of_birth')
compare_cl.exact('suburb', 'suburb', label='suburb')
compare_cl.exact('state', 'state', label='state')
compare_cl.string('address_1', 'address_1', threshold=0.85, label='address_1')

In [14]:
## The comparing of record pairs starts when the compute method is called. 
## All attribute comparisons are stored in a DataFrame with horizontally the features and vertically the record pairs.

features = compare_cl.compute(pairs, dfA, dfB)
features.head()

                             given_name  surname  date_of_birth  suburb  \
rec_id       rec_id
rec-1070-org rec-1070-dup-0         1.0      0.0              1       0
             rec-1124-dup-0         0.0      0.0              0       0
rec-1124-org rec-1070-dup-0         0.0      0.0              0       0
             rec-1124-dup-0         1.0      1.0              1       1
rec-1016-org rec-4695-dup-0         0.0      0.0              0       0

                             state  address_1
rec_id       rec_id
rec-1070-org rec-1070-dup-0      0        1.0
             rec-1124-dup-0      1        0.0
rec-1124-org rec-1070-dup-0      0        0.0
             rec-1124-dup-0      1        1.0
rec-1016-org rec-4695-dup-0      0        0.0

In [15]:
features.head()

                             given_name  surname  date_of_birth  suburb  \
rec_id       rec_id
rec-1070-org rec-1070-dup-0         1.0      0.0              1       0
             rec-1124-dup-0         0.0      0.0              0       0
rec-1124-org rec-1070-dup-0         0.0      0.0              0       0
             rec-1124-dup-0         1.0      1.0              1       1
rec-1016-org rec-4695-dup-0         0.0      0.0              0       0

                             state  address_1
rec_id       rec_id
rec-1070-org rec-1070-dup-0      0        1.0
             rec-1124-dup-0      1        0.0
rec-1124-org rec-1070-dup-0      0        0.0
             rec-1124-dup-0      1        1.0
rec-1016-org rec-4695-dup-0      0        0.0

In [16]:
features.describe()

,given_name,surname,date_of_birth,suburb,state,address_1
count,28609.000000,28609.000000,28609.000000,28609.000000,28609.000000,28609.000000
mean,0.122619,0.130973,0.131322,0.109581,0.327694,0.126813
std,0.328005,0.337376,0.337758,0.312372,0.469381,0.332769
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Classification

Now we have to decide which records belong to one person. We can do this pretty simple, but we can also use machine learning methods to classify records.

In [17]:
## Simple Classification: Check for how many attributes records are identical by summing the comparison results.
features.sum(axis=1).value_counts().sort_index(ascending=False)

6.0     1576
5.0     1656
4.0      745
3.0      207
2.0      101
1.0     5611
0.0    18713
dtype: int64

In [18]:
matches = features[features.sum(axis=1) > 3]
print(len(matches))

3977

Now let's do this with a machine learning classifier. Keep in mind that most classifiers can not handle comparison vectors with missing values. To prevent issues with the classification algorithms. Supervised learning algorithms do need training data. Training data is data for which the true match status is known for each comparison vector. In the example in this section, we consider that the true match status of the first 5000 record pairs of our data is known.

In [19]:
## Generate Training Data and index
ml_pairs = matches[0:1000]
ml_matches_index = ml_pairs.index & pairs

The Naive Bayes classifier is a probabilistic classifier. The probabilistic record linkage framework by Fellegi and Sunter (1969) is the most well-known probabilistic classification method for record linkage. Later, it was proved that the Fellegi and Sunter method is mathematically equivalent to the Naive Bayes method in case of assuming independence between comparison variables.

In [20]:
## Train the classifier
nb = recordlinkage.NaiveBayesClassifier()
nb.learn(ml_pairs, ml_matches_index)

## Predict the match status for all record pairs
result_nb = nb.predict(matches)

## Predict probability for record to be a match
prob_nb = nb.prob(matches)

In [21]:
## Check header
prob_nb.head()

rec_id        rec_id
rec-1124-org  rec-1124-dup-0    1.0
rec-1016-org  rec-1016-dup-0    1.0
rec-4695-org  rec-4695-dup-0    1.0
rec-4158-org  rec-4158-dup-0    1.0
rec-4100-org  rec-4100-dup-0    1.0
dtype: float64

## Evaluation

The last step is to evaluate the results of the record linkage.

In [22]:
## Confusion matrix
conf_nb = recordlinkage.confusion_matrix(pairs, result_nb, len(features))
conf_nb

array([[ 3977, 24632],
       [    0,     0]])

In [23]:
## Precision and Accuracy
precision = recordlinkage.precision(conf_nb)
accuracy = recordlinkage.accuracy(conf_nb)

In [24]:
print(precision)

1.0

In [25]:
print(accuracy)

0.139012198958

In [26]:
## The F-score for this classification is
recordlinkage.fscore(conf_nb)

0.24409255508500585